### ISSUE TITLE
Import into Wireshark

### ISSUE THREAD

**Issue by Poohl** [Yamakaky/joy#1]
Hey, thanks for the captures and script.

I wrote a plugin for Wireshark analyzing the traffic: https://github.com/dekuNukem/Nintendo_Switch_Reverse_Engineering/tree/master/packet_parse/nxbt and would like to use it to analyze the captures. Do you know of any easy method to get these captures into Wireshark? Your format seems to be really easy to parse, but the import-from-hex in Wireshark seems to only support some messed up format that isn't even easy to convert to.

If no feel free to close this Issue, I'll figure something out to create Wireshark's weird mess.

**Comment by Yamakaky** [comment]
Since I use my software to parse the traffic, I haven't looked at wireshark so you would have to redo the capture. If you don't have a ringcon, I can do one myself.

Doing a joycon wireshark plugin seems doable, could be fun ^^

**Comment by Poohl** [comment]
I'm happy about any capture including MCU functionality, as far as I know that is IR, NFC, Firmware-Updates. Not sure about the Ringcon, might be, might not be.

If you want to help with the plugin, feel free. I'm currently not working on this code, as it already does most NFC specific stuff as good as I understand it. If you want to (or don't wat to recompile Wireshark), all of this can also be done in LUA aswell. Porting should be easy but the documentation isn't as comprehensive.

**Comment by Poohl** [comment]
FYI: I added the necassary import feature to wireshark: https://gitlab.com/paulniklasweiss/wireshark/-/tree/regex_text_import (under file->import from Hex dump)

The regex to import your dump format is something like `$(?<dir>[<>])\s*(?<time>[0-9\.:]+)\s+(?<data>[0-9a-fA-F])^` and the timestamp is `%H:%M:%S.%f`

**Comment by Yamakaky** [comment]
Interesting. What are the advantagesto import it? I assume Wireshark doesn't understand the hid protocol?

**Comment by Poohl** [comment]
Wireshark understands HID, but not Nintendos additions and alternate modes.

I wrote a plugin for it to understand (parts of) the protocoll ([nxbt](https://github.com/Poohl/Nintendo_Switch_Reverse_Engineering/tree/nxbt_wireshark_plugin/packet_parse/nxbt))

But yes, the plugin just replaces the Bluetooth-HID-plugin and doesn't expand it. It also isn't very complete, just parsing Subcommands and some of the NFC stuff.

The advantage with this however is giant, as you can just filter for e.g. `nxbt.mcu.nfc.state == 0x03` and in this case get all responses sent by the joycon in writing mode.
