### ISSUE TITLE
Make some features optional

### ISSUE THREAD

**Issue by pickfire** [Yamakaky/joy#16]
I noticed some features like `image` in `joycon` can be optional, it would be nice if it can enabled via a feature.

Currently I am using joycon for https://github.com/pickfire/joycon-cemuhook, for cemuhook protocol support, reviews are welcome. I feel like it is a good candidate to be added to this repository once it is more mature.

I found this crate through https://gitlab.com/gilrs-project/gilrs/-/issues/106 but it seemed quite usable to me.

**Comment by Yamakaky** [comment]
Sure, `image` is used for the infrared sensor on the joycon. I'll see that.

For the root part, check https://github.com/Yamakaky/gyromouse#linux=.

**Comment by Yamakaky** [comment]
Done!
