### ISSUE TITLE
add support for linux driver

### ISSUE THREAD

**Issue by ImUrX** [Yamakaky/joy#17]

**Comment by Yamakaky** [comment]
What do you mean by that? It already works on linux

**Comment by ImUrX** [comment]
[they added their own driver with imu support](https://github.com/torvalds/linux/blob/e08466a7c00733a501d3c5328d29ec974478d717/drivers/hid/hid-nintendo.c)

**Comment by ImUrX** [comment]
but im just gonna use it directly in linux, its not that simple but not that hard

**Comment by Yamakaky** [comment]
I'm not sure what you are suggesting we do. The linux driver implements a gamepad while `joycon` is low level and can send raw reports. What usecase do you see missing?

**Comment by ImUrX** [comment]
yeah i will just close it, the ``evdev`` implementation wasnt hard to use and their data is the same as raw
